### PR TITLE
Korean translation for new menu items

### PR DESCRIPTION
**Pull request by sh1217sh**
Korean translation for new menu items.
Also, I think we should consider about the names and the order of the menu items. I think it can cause confusion to the users.

### CODE REVIEW

**Comment by milgra** [comment]
thank you! I feel the same about the names and order.

**Comment by milgra** [comment]
I've made some changes to the ux/menu items, can you please re-translate the two new menu items? thank you!

**Comment by sh1217sh** [comment]
Done. Made PR #26 :)

**Comment by milgra** [comment]
yaay, thank you! :)

**Pull request merged**
