### PR TITLE
- added standard player selection

### PR DESCRIPTION
**Pull request by michaeldorner**
- fixed issue with Spotify and iTunes installed at the same time (issue #3 )
- updated to Xcode 9
- removed `README.MD` Build Phase
- (optional) added Travis support

### CODE REVIEW

**Comment by milgra** [comment]
Hi, thank you for the pull request, but why would anyone run iTunes and Spotify at the same time? You cannot listen to two music sources simultaneously. Or quitting apps on MacOS is not so common any more and selecting between the two seems a better solution?

**Comment by ggascoigne** [comment]
I have to say that I often have them both running at the same time, but I also run my laptop for months on end without a reboot. But in the general case I would expect the keys to go to the last one of the two that I’d actively started playing from.

**Comment by michaeldorner** [comment]
A use case which came to my mind: Using iTunes for backing up the iPhone, while listen to Spotify.

**Comment by milgra** [comment]
All features from this pull request are in the app now, thank you!

**Pull request closed without merging**
